### PR TITLE
Fix vectorized version of bli_amaxv

### LINKED ISSUE #380: Incorrect amaxv results
(This supersedes #379.)

I'm using

```
$ ./configure -d CC=gcc auto
configure: detected Linux kernel version 5.5.8-200.fc31.x86_64.
configure: python interpeter search list is: python python3 python2.
configure: using 'python' python interpreter.
configure: found python version 3.7.6 (maj: 3, min: 7, rev: 6).
configure: python 3.7.6 appears to be supported.
configure: C compiler search list is: gcc clang cc.
configure: using 'gcc' C compiler.
configure: C++ compiler search list is: g++ clang++ c++.
configure: using 'g++' C++ compiler (for sandbox only).
configure: found gcc version 9.2.1 (maj: 9, min: 2, rev: 1).
configure: checking for blacklisted configurations due to gcc 9.2.1.
configure: checking gcc 9.2.1 against known consequential version ranges.
configure: found assembler ('as') version 2.32 (maj: 2, min: 32, rev: ).
configure: checking for blacklisted configurations due to as 2.32.
configure: reading configuration registry...done.
configure: determining default version string.
configure: found '.git' directory; assuming git clone.
configure: executing: git describe --tags.
configure: got back 0.6.1-5-gc01d249d.
configure: truncating to 0.6.1-5.
configure: starting configuration of BLIS 0.6.1-5.
configure: configuring with official version string.
configure: found shared library .so version '3.0.0'.
configure:   .so major version: 3
configure:   .so minor.build version: 0.0
configure: automatic configuration requested.
configure: hardware detection driver returned 'haswell'.
configure: checking configuration against contents of 'config_registry'.
configure: configuration 'haswell' is registered.
configure: 'haswell' is defined as having the following sub-configurations:
configure:    haswell
configure: which collectively require the following kernels:
configure:    haswell zen
configure: checking sub-configurations:
configure:   'haswell' is registered...and exists.
configure: checking sub-configurations' requisite kernels:
configure:   'haswell' kernels...exist.
configure:   'zen' kernels...exist.
configure: no install prefix option given; defaulting to '/usr/local'.
configure: no install exec_prefix option given; defaulting to PREFIX.
configure: no install libdir option given; defaulting to EXECPREFIX/lib.
configure: no install includedir option given; defaulting to PREFIX/include.
configure: no install sharedir option given; defaulting to PREFIX/share.
configure: final installation directories:
configure:   prefix:      /usr/local
configure:   exec_prefix: ${prefix}
configure:   libdir:      ${exec_prefix}/lib
configure:   includedir:  ${prefix}/include
configure:   sharedir:    ${prefix}/share
configure: NOTE: the variables above can be overridden when running make.
configure: no preset CFLAGS detected.
configure: no preset LDFLAGS detected.
configure: enabling debug symbols; optimizations disabled.
configure: disabling verbose make output. (enable with 'make V=1'.)
configure: disabling ARG_MAX hack.
configure: building BLIS as both static and shared libraries.
configure: exporting only public symbols within shared library.
configure: threading is disabled.
configure: requesting slab threading in jr and ir loops.
configure: internal memory pools for packing blocks are enabled.
configure: internal memory pools for small blocks are enabled.
configure: memory tracing output is disabled.
configure: libmemkind not found; disabling.
configure: compiler appears to support #pragma omp simd.
configure: the BLAS compatibility layer is enabled.
configure: the CBLAS compatibility layer is disabled.
configure: mixed datatype support is enabled.
configure: mixed datatype optimizations requiring extra memory are enabled.
configure: small matrix handling is enabled.
configure: the BLIS API integer size is automatically determined.
configure: the BLAS/CBLAS API integer size is 32-bit.
configure: configuring for conventional gemm implementation.
configure: creating ./config.mk from ./build/config.mk.in
configure: creating ./bli_config.h from ./build/bli_config.h.in
configure: creating ./obj/haswell
configure: creating ./obj/haswell/config/haswell
configure: creating ./obj/haswell/kernels/haswell
configure: creating ./obj/haswell/kernels/zen
configure: creating ./obj/haswell/ref_kernels/haswell
configure: creating ./obj/haswell/frame
configure: creating ./obj/haswell/blastest
configure: creating ./obj/haswell/testsuite
configure: creating ./lib/haswell
configure: creating ./include/haswell
configure: mirroring ./config/haswell to ./obj/haswell/config/haswell
configure: mirroring ./kernels/haswell to ./obj/haswell/kernels/haswell
configure: mirroring ./kernels/zen to ./obj/haswell/kernels/zen
configure: mirroring ./ref_kernels to ./obj/haswell/ref_kernels
configure: mirroring ./ref_kernels to ./obj/haswell/ref_kernels/haswell
configure: mirroring ./frame to ./obj/haswell/frame
configure: creating makefile fragments in ./obj/haswell/config/haswell
configure: creating makefile fragments in ./obj/haswell/kernels/haswell
configure: creating makefile fragments in ./obj/haswell/kernels/zen
configure: creating makefile fragments in ./obj/haswell/ref_kernels
configure: creating makefile fragments in ./obj/haswell/frame
configure: configured to build within top-level directory of source distribution.
```
on Core i9.

The following Fortran program shows incorrect results for i*amax:

```
Program p
  Real, Allocatable :: f(:)
  Double Precision, Allocatable :: x(:)
  Character (:), Allocatable :: c
  x = [ (42.D0,i=1,4) ]
  c = ' double, constant'
  Print *, merge('PASS', 'FAIL', idamax(size(x),x,1)==1)//c
  f = [ (42.E0,i=1,4) ]
  c = ' float, constant'
  Print *, merge('PASS', 'FAIL', isamax(size(f),f,1)==1)//c
  x = [ Double Precision :: 8, -7, 9, 5, 9, 8, 7, 7 ]
  c = ' double'
  Print *, merge('PASS', 'FAIL', idamax(size(x),x,1)==3)//c
  f = [ Real :: 8, -7, 9, 5, 9, 8, 7, 7 ]
  c = ' float'
  Print *, merge('PASS', 'FAIL', isamax(size(f),f,1)==3)//c
End Program
```
in which the smallest of the max indices are not being returned:

```
 FAIL double, constant
 PASS float, constant
 FAIL double
 FAIL float
```

### PR DESCRIPTION
**Pull request by devinamatthews**
To match Netlib, i?amax should return:
- the lowest index among equal values
- the first NaN if one is encountered

Fixes #380.

### CODE REVIEW

**Comment by devinamatthews** [comment]
@fgvanzee I wrote this in the browser so someone should make sure it even compiles :smile:. Also, it is not super pretty since the logic is rather complicated but I think this is about as good as it is going to get.

**Comment by devinamatthews** [comment]
OK, doesn't compile. Will fix tomorrow.

**Comment by devinamatthews** [comment]
Tested, and ref. kernel fixed too. Ready to merge after review.

**Comment by fgvanzee** [comment]
@devinamatthews @rvdg Okay, this would have taken me *way* longer than an hour. Thanks for this PR.

It looks fine to me, although I haven't looked at the intrinsics code closely enough to know *why* it works. :)

I'm assuming you re-enabled the use of the kernels while testing? (Dumb question, I know, but I'm just making sure since you didn't include the re-enabling of the kernels in this PR.)

**Comment by fgvanzee** [comment]
@devinamatthews Just to confirm (per this https://github.com/flame/blis/issues/385#issuecomment-603463103): this commit should reenable the intrinsics `amaxv` kernel disabled by e186d71? If so, I can push a commit to this PR and then squash-merge.

**Comment by devinamatthews** [comment]
@fgvanzee yes.

**Pull request merged**
