### PR TITLE
Fix Cortex-A9 and Cortex-A15 configs.

### LINKED ISSUE #170: ARM builds fail
On 03/12/18 09:27, Jacob Gorm Hansen wrote:
> On Sunday, March 11, 2018 at 11:22:40 PM UTC+1, Field Van Zee wrote:
>> Jacob,
>>
>> I have corrected the typos in 1442d06. Now, this may not be the *only* error standing in your way, but it definitely needed to get fixed. Please give it a try.
>
> It now gets a bit further, but ultimately dies with:
>
> Compiling obj/cortexa57/frame/base/bli_func.o ('cortexa57' CFLAGS for framework code)
> frame/base/bli_cpuid.c: In function "bli_cpuid_query_id":
> frame/base/bli_cpuid.c:54:17: error: "VENDOR_INTEL" undeclared (first use in this function); did you mean "VENDOR_ARM"?
>   if ( vendor == VENDOR_INTEL )
>                  ^~~~~~~~~~~~
>                  VENDOR_ARM
> compilation terminated due to -Wfatal-errors.
> make[1]: *** [Makefile:462: obj/cortexa57/frame/base/bli_cpuid.o] Error 1

Jacob: I've committed 1a303174, which hopefully addresses some of the issues. Please try it out and let me know the outcome.

### PR DESCRIPTION
**Pull request by devinamatthews**
Tested with QEMU. Fixes #170.

### CODE REVIEW

**Comment by devinamatthews** [comment]
@fgvanzee shall I go ahead and merge? The only possible point of contention is that I re-enabled the makefile rules for .s and .S.

**Comment by fgvanzee** [comment]
@devinamatthews I can't see how it would hurt to enable rules for `.s` and `.S` files. I see you also caught and fixed a stale reference to `$(MK_HEADER_FILES)` that should have been `$(BLIS_H_FLAT)`. Thanks!

**Comment by devinamatthews** [comment]
I actually did the opposite, but it is fixed now. Merging.

**Comment by jacobgorm** [comment]
Just to confirm that both the cortexa15 and 'cortexa57 configure & build pass for me now. Thanks a bunch.

**Pull request merged**
