### PR TITLE
Partial addition of `const` to all interfaces above the level of the (micro)kernels.

### PR DESCRIPTION
**Pull request by devinamatthews**

### CODE REVIEW

**Comment by devinamatthews** [comment]
Needs one more tweak, hold on.

**Comment by fgvanzee** [comment]
No rush. I only merged `mr_nr_macros` into this PR branch to work through existing conflicts.

**Comment by devinamatthews** [comment]
@fgvanzee looks like both the `zen` and `zen2` subconfigs have `bli_axpyf_zen_int_5.c`, which is causing problems with the `x86_64` build.

**Comment by devinamatthews** [comment]
Also, I don't know why Travis is not triggering. Are we out of credits?

**Comment by fgvanzee** [comment]
> @fgvanzee looks like both the `zen` and `zen2` subconfigs have `bli_axpyf_zen_int_5.c`, which is causing problems with the `x86_64` build.

Thanks. That file was supposed to be moved to `zen` from `zen2`, not copied. I can fix.

> Also, I don't know why Travis is not triggering. Are we out of credits?

We have plenty of credits. Sometimes Travis does this. No idea why. My guess is that it's not not triggering, just not triggering immediately.

**Comment by fgvanzee** [comment]
Yay conflicts gone. Now time to finish the actual code review. :upside_down_face:

**Comment by devinamatthews** [comment]
Finally got Travis to trigger a build. I think maybe being a draft messed it up?

**Pull request closed without merging**
