### PR TITLE
Add optimized packing kernels.

### PR DESCRIPTION
**Pull request by devinamatthews**
Added SSE2 kernels for dunnington and AVX kernels for sandybridge/haswell. New kernels are enable for all of the configurations and have all been tested.

### CODE REVIEW

**Comment by devinamatthews** [comment]
OK, so it's only good for something like 1%, but oh well.

**Comment by jeffhammond** [comment]
1% in DGEMM is not insignificant...

**Comment by devinamatthews** [comment]
Apparently that 1% is more like +/- 1%...  also tried SW prefetches and that has a more or less random effect on performance as well. I'm going to close this until we understand the ramifications better.

**Comment by fgvanzee** [comment]
Thanks for looking into this, Devin. Your experience is consistent with what I seem to remember from my (albeit dated) experiments with optimized packing. (That is, optimizing packing is harder than it looks, unfortunately.)

**Pull request closed without merging**
