### PR TITLE
Support for Intel Knight's Landing

### PR DESCRIPTION
**Pull request by devinamatthews**

### CODE REVIEW

**Comment by jeffhammond** [comment]
I am testing this on a DOE KNL system just to verify.

It's not surprising, but one needs to compiler this on a KNL system to be sure of getting `hbwmalloc.h`, although one can install [memkind](https://github.com/memkind/memkind) on any Linux system to enable cross-compilation, provided the toolchain knows about the KNL ISA.

**Comment by jeffhammond** [comment]
All tests pass on a 7250 part.

**Comment by jeffhammond** [comment]
GCC 6.2.0 also passes all the tests.  While I have the permissions to do so, I will let @fgvanzee hit the merge button.

**Comment by devinamatthews** [comment]
@jeffhammond in case Intel is keeping score, llvm sucks hard on AVX512 (at least 3.8.1 does).

**Comment by devinamatthews** [comment]
It botches many of the instruction encodings unpredictably, especially wrt compressed disp8.

**Comment by jeffhammond** [comment]
> It botches many of the instruction encodings unpredictably, especially wrt
> compressed disp8.
>
>
I'll see if anyone internally knows about this.


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by tlrmchlsmth** [comment]
Devin,

Were they written in intrinsics or assembly?

-Tyler

**Comment by devinamatthews** [comment]
Assembly.

**Comment by jeffhammond** [comment]
I can't find the option, but I wonder if you can change the assembler that Clang->LLVM uses.

https://llvm.org/bugs/ requires work to sign up but it would be ideal if you could post this bug report their.

If all else fails, I'll see if @hfinkel is willing to help us diagnose this.  He should have a strong interest in LLVM+AVX512+HPC.

**Comment by hfinkel** [comment]
Regarding LLVM, you should try 3.9. 3.8.x was not really usable for AVX-512. If you're still seeing problems, I'm happy to help.

**Comment by jeffhammond** [comment]
Thanks @hfinkel.  I'm going to build the latest LLVM from source and see if that works.

**Comment by devinamatthews** [comment]
Now I don't know how I even got it to compile before. With clang 3.8.1 (on OSX, but I don't think that should matter, right?):

```
/Users/dmatthews/src/blis/config/knl/kernels/1m/bli_packm_opt_24x8.c:280:11: error: unknown register name 'zmm0' in asm
          "zmm0", "zmm1", "zmm2", "zmm3", "zmm4", "zmm5",
```

And with 3.9.0 (on actual HW):

```
/home/dmatthews/src/blis/config/knl/kernels/1m/bli_packm_opt_24x8.c:221:13: error: invalid % escape in inline assembly string
            LOADMUL8x8_MASK(RAX,0,RBX,R8,R9,R10,0,1,2,3,4,5,6,7,1)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dmatthews/src/blis/config/knl/kernels/1m/bli_packm_opt_24x8.c:53:5: note: expanded from macro 'LOADMUL8x8_MASK'
    VMULPD(ZMM(z0) MASK_KZ(k), ZMM(31), MEM(a,     o)) \
    ^
/home/dmatthews/src/blis/config/knl/kernels/1m/bli_avx512_macros.h:118:28: note: expanded from macro 'VMULPD'
#define VMULPD(_0, _1, _2) ASM(vmulpd _2, _1, _0)
                           ^
/home/dmatthews/src/blis/config/knl/kernels/1m/bli_avx512_macros.h:12:18: note: expanded from macro 'ASM'
#define ASM(...) STRINGIFY(__VA_ARGS__) "\n\t"
                 ^
/home/dmatthews/src/blis/config/knl/kernels/1m/bli_avx512_macros.h:11:24: note: expanded from macro 'STRINGIFY'
#define STRINGIFY(...) #__VA_ARGS__
                       ^
<scratch space>:23:38: note: expanded from here
"vmulpd 0(%%rax), %% zmm31, %% zmm0 %{ %% k1 %} %{z%}"
```

**Comment by jeffhammond** [comment]
@devinamatthews I build Clang/LLVM from source (see below for details) and verified that all of `auto reference dunnington sandybridge haswell knl` are working fine on Haswell (all but `knl`) and KNL (`knl`, obviously).

Interestingly enough, I did hit a compiler bug along the way, but it was that GCC 4.8.3-9 ICEd when trying to compile the LLVM C++ library 😆  GCC 6.2.0 had no trouble compiling LLVM.

It was not hard to build LLVM from source.  You can use the following.
```sh
#!/bin/bash -ex

export LLVM_TOP=$HOME/LLVM

mkdir -p $LLVM_TOP

cd $LLVM_TOP
git clone http://llvm.org/git/llvm.git
cd $LLVM_TOP/llvm
git config branch.master.rebase true

cd $LLVM_TOP/llvm/tools
git clone http://llvm.org/git/clang.git

cd $LLVM_TOP/llvm/projects
git clone http://llvm.org/git/compiler-rt.git

cd $LLVM_TOP/llvm/projects
git clone http://llvm.org/git/openmp.git

cd $LLVM_TOP/llvm/projects
git clone http://llvm.org/git/libcxx.git
git clone http://llvm.org/git/libcxxabi.git

cd $LLVM_TOP/llvm/projects
git clone http://llvm.org/git/test-suite.git

cd $LLVM_TOP/llvm
mkdir -p $LLVM_TOP/llvm/build
cd $LLVM_TOP/llvm/build
cmake ..  -G "Unix Makefiles" \
    -DCMAKE_INSTALL_PREFIX=$HOME/LLVM/install \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TARGETS_TO_BUILD=X86
make -j12
make -j12 install
```

**Comment by devinamatthews** [comment]
The 3.9.0 was built from source, 3.8.1 from homebrew.

**Comment by jeffhammond** [comment]
@devinamatthews If you see problems on Mac, I have to blame Apple and their toolchain for that, because Clang/LLVM has no issues on Linux.  I'm not saying that I enjoy Apple providing a bad toolchain for AVX-512, since I too have a Mac as my primary development platform, but I can't say that I blame them if their assembler and/or linker can't handle AVX-512 instructions.

**Comment by devinamatthews** [comment]
Can you check the disassembly of the KNL microkernel with clang and 
verify that it is not emitting 10 and 11-byte FMAs?

**Pull request merged**
