### PR TITLE
Reinstate sanity check in bli_pool_finalize.

### PR DESCRIPTION
**Pull request by devinamatthews**
Reinstate check for checked-out blocks upon finalization. A flag has been added to indicate that the pool is actually under reinitialization (where checked-out blocks are OK), which temporarily disables the check. A memory leak where blocks are not checked back in is now correctly detected upon exit.

### CODE REVIEW

**Comment by devinamatthews** [comment]
@fgvanzee another fix for bli_pool.

**Comment by fgvanzee** [comment]
Can you talk a little bit more about what happened here? Was it that both the original check and your previous fix were incomplete, and we needed to somehow handle both?

**Comment by devinamatthews** [comment]
The previous PR prevented a segfault when certain conditions happened (in my case, a memory leak). This PR reinstates the check necessary to detect the memory leak instead of exiting successfully. It also avoids a spurious check when reinitializing the pool in mid-computation.

**Comment by fgvanzee** [comment]
Okay, I think I understand now. Thanks.

**Pull request merged**
