### PR TITLE
Arm64 & ArmSVE: Remove Generic Stride Assembly

### PR DESCRIPTION
**Pull request by xrq-phys**
I removed asm-level generic stride support from `armv8a` & `armsve` kernels to cope with #583 .

- [x] Test for NEON.
- [x] Test for SVE.
- [x] ~Use predicates.~ Use predicates only in `m`-dimension.

### CODE REVIEW

**Comment by xrq-phys** [comment]
@devinamatthews Hi Devin.

Sorry for this 1-month delay. I guess I've put SVE kernels into a better form for #583 .

**Comment by xrq-phys** [comment]
zgemm

**Comment by devinamatthews** [comment]
@xrq-phys looks like the problem I had in #609 is fixed by appending `%=` to labels as we did on mac. Can you update **this** PR to add `%=` to all armsve/a64fx labels so I don't get a messy merge by doing it in #609?

Otherwise, is this PR ready to go?

**Comment by xrq-phys** [comment]
@devinamatthews Adopted the same set of labeling macros as for Apple. Hope I didn't miss up any instruction.

**Pull request merged**
