### PR TITLE
Partial addition of `const` to all interfaces above the level of the (micro)kernels.

### PR DESCRIPTION
**Pull request by devinamatthews**
#619 was based on `mr_nr_macros`, not `master`.

### CODE REVIEW

**Comment by devinamatthews** [comment]
@fgvanzee fixed some merge conflicts, tests running now. Sorry about the merge target mixup.

**Comment by fgvanzee** [comment]
> @fgvanzee fixed some merge conflicts, tests running now. Sorry about the merge target mixup.

Are you referring to the fact that #619 wants to merge `const-roundup` into `mr_nr_macros`?

**Comment by fgvanzee** [comment]
> Yes, thus the new PR. Can't seem to change the target after creating the PR.

Ah, okay, thanks. I assumed it was intentional. :slightly_smiling_face:

**Comment by fgvanzee** [comment]
I'm currently testing my changes to this PR. What do you make of this warning?
```
Compiling obj/haswell/ref_kernels/haswell/3/bli_gemmsup_haswell_ref.o ('haswell' CFLAGS for ref. kernels)
In file included from ref_kernels/3/bli_gemm_ref.c:35:
ref_kernels/3/bli_gemm_ref.c: In function ‘bli_cgemm_haswell_ref’:
include/haswell/blis.h:7895:30: warning: ‘ab[<unknown>].real’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 7895 | #define bli_creal( x )  ( (x).real )
      |                              ^
include/haswell/blis.h:7896:30: warning: ‘ab[<unknown>].imag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 7896 | #define bli_cimag( x )  ( (x).imag )
      |                              ^
```

**Comment by devinamatthews** [comment]
It's spurious, but I haven't been able to get it to go away. The "hammer" solution is adding `-Wno-maybe-unitialized`.

**Comment by fgvanzee** [comment]
Okay, thanks. Silly `gcc`.

**Review by devinamatthews — COMMENTED** [review]
What's funny is a lot of these spaces I didn't put in there...

**Comment by fgvanzee** [comment]
> What's funny is a lot of these spaces I didn't put in there...

Could they be spaces I inserted in 3b4cb00?

**Comment by devinamatthews** [comment]
I think they're just been there forever.

**Comment by fgvanzee** [comment]
I see. I'm pretty happy with the whitespace formatting, both before and after my edits.

**Comment by fgvanzee** [comment]
Woot. Any last minute things you want to include in this PR branch before I squash?

**Comment by fgvanzee** [comment]
@devinamatthews Also, is it correct to characterize this PR as adding `const` to *all* interfaces above the (micro)kernels, or to all *user* interfaces above the (micro)kernels? Or something else?

I'd like to try to capture the scope of the `const`ification (as reasonably as possible) in the commit log entry.

**Comment by devinamatthews** [comment]
I would say *all* interfaces. The internal ones are important for enforcing correct usage withing the framework.

**Pull request merged**
