### PR TITLE
Implement missing pthreads function on Windows

### LINKED ISSUE #247: Remove requirement for pthreads if single-threaded?
Currently even with `--disable-threading`, the library won't build without `pthreads.h`. This is quite a hassle on Windows, since all the options for getting a library like this are pretty inconvenient.

It also seems the pthreads for Windows library is LGPL, which means Blis can't be a dependency for an MIT/BSD/Apache-licensed library that supports Windows.

I think this problem shouldn't be too hard to solve. It looks to me like there are just a few places where the pthreads.h include isn't guarded behind conditionals properly. The other branch of the conditional compilation will also need to add a couple of typedefs that would otherwise be missing.

### PR DESCRIPTION
**Pull request by devinamatthews**
Implement pthreads mutexes and one-time initialization using Windows primitives to avoid pthreads dependency. Fixes #247. In the current state, pthreads-dependence of the testsuite driver is not addressed. Also, it has not been tested.

### CODE REVIEW

**Comment by honnibal** [comment]
There's a small typo, `callpack` (should be `callback`). Fixing it gives the next error:

```
frame/base/bli_pthread_wrap.c:137:43: fatal error: too few arguments to function call, expected 2, have 1
1092    if (!WaitForSingleObject(thread.handle)) return EAGAIN;
1093         ~~~~~~~~~~~~~~~~~~~              ^
1094
```

**Comment by honnibal** [comment]
Likely the last error: there's still a stray `-lpthreads` flag somewhere for the shared library:

```
lang -O3 -Wno-macro-redefined -Wall -Wno-unused-function -Wfatal-errors -Wno-tautological-compare -std=c99 -D_POSIX_C_SOURCE=200112L -Iinclude/x86_64 -I./frame/3/ -I./frame/ind/ukernels/ -I./frame/1m/ -I./frame/1f/ -I./frame/1/ -I./frame/include -DBLIS_VERSION_STRING=\"0.4.1-33\" -DBLIS_IS_BUILDING_LIBRARY -c frame/util/bli_util_unb_var1.c -o obj/x86_64/frame/util/bli_util_unb_var1.o
1346clang -shared -Wl,-def:windows/build/libblis-symbols.def -Wl,-implib:lib/x86_64/libblis.lib -lpthread -o lib/x86_64/libblis.1.dll @lib/x86_64/libblis.lib.in
1347LINK : fatal error LNK1181: cannot open input file 'pthread.lib'
1348clang.exe: error: linker command failed with exit code 1181 (use -v to see invocation)
1349Makefile:629: recipe for target 'lib/x86_64/libblis.lib' failed
1350make: *** [lib/x86_64/libblis.lib] Error 157
1351
```

https://ci.appveyor.com/project/honnibal/blis/build/job/ecqs9y2y3o0nm2qw

**Comment by honnibal** [comment]
Apart from this linking error, I think this is probably all working. Tests are passing on Windows for my Python bindings (specifically, I'm calling gemm and dotv with random values and checking the result matches numpy).

The Appveyor script can also be simplified (and made faster) by using the version of LLVM that's already installed on Appveyor, LLVM 7.0. LLVM 7 was missing fenv.h, but simply adding the header seemed to work. This avoids the need to use conda, which is super slow.

**Comment by devinamatthews** [comment]
Is `$LIBPTHREAD` getting set to null or blank appropriately? Maybe since this is "pseudo-unix" it should be set to something like " " (space) to make sure it doesn't get defaulted to -lpthread.

**Comment by isuruf** [comment]
There's a `is_win` variable set in the configure that you could use.

Does this PR mean that if a user wants to use pthreads-win32 on windows, they can't?

**Comment by fgvanzee** [comment]
Just checking on the status of this PR (in advance of pre-release cleanups). I see that it failed the Appveyor tests. But I can't seem to get any details from Appveyor via the "Details" links above.

**Comment by devinamatthews** [comment]
@fgvanzee let's see if 0b73209 fixes it. @isuruf yes this PR means that "pthreads" on Windows is really just WinThreads. Of course, pthreads-win32 would also be based on WinThreads internally so I think there is really very little difference (apart from possible bugs...).

**Comment by devinamatthews** [comment]
Correction 29e6245 is the one to watch (merge conflict).

**Comment by devinamatthews** [comment]
OK, the `auto` build is failing because `pthread_once` is not linked. @fgvanzee would it be easier to link the `frame/base/bli_pthread_wrap.o` object into the auto-detect binary or supply a simple (non-thread-safe because it doesn't need to be) implementation in the auto-detector?

@honnibal @isuruf do either of you know what is causing the linker error in the `x86-64` build? Other than that it seems to compile successfully.

**Comment by fgvanzee** [comment]
> OK, the `auto` build is failing because `pthread_once` is not linked. @fgvanzee would it be easier to link the `frame/base/bli_pthread_wrap.o` object into the auto-detect binary or supply a simple (non-thread-safe because it doesn't need to be) implementation in the auto-detector?

I'm leaning towards the idea of a simple non-thread-safe version. Linking in framework files can be tricky, but maybe it wouldn't be in this case since it `bli_pthread_wrap.c` probably doesn't need to depend on anything like `blis.h`. What do you think?

**Comment by devinamatthews** [comment]
Even simpler than that: `pthread_once` isn't actually used it's just in the same file as another function that is needed. So, I conditionally compiled that line.

In the `x86-64` build, looking at the logs for `master` it looks like maybe the .def file is just out of date due to the multiple precision stuff.

**Comment by fgvanzee** [comment]
> Even simpler than that: pthread_once isn't actually used it's just in the same file as another function that is needed. So, I conditionally compiled that line.

Lovely. That's probably the highlight of my day since I'm now fighting a segfault from merging `master` into `mixeddt`. :-\

> In the `x86-64` build, looking at the logs for `master` it looks like maybe the .def file is just out of date due to the multiple precision stuff.

Could you provide me with a link? I still can't figure out how to navigate the Appveyor build pages.

**Comment by devinamatthews** [comment]
https://ci.appveyor.com/project/shpc/blis/builds/19552287/job/dpkkludt0c93esug

**Comment by devinamatthews** [comment]
FYI if you click on "Details" in the CI box (just above this comment box), then go to "History" you can see all of the builds referenced by commit. Then click on the individual build job to see the log.

**Comment by fgvanzee** [comment]
> FYI if you click on "Details" in the CI box (just above this comment box), then go to "History" you can see all of the builds referenced by commit. Then click on the individual build job to see the log.

I can get that far, but I don't see any log files.

**Comment by fgvanzee** [comment]
> https://ci.appveyor.com/project/shpc/blis/builds/19552287/job/dpkkludt0c93esug

Visiting this link was helpful. It's actually not related to any mixed datatype stuff. The problem is that I renamed macrokernels according to whether they used round-robin or slab partitioning in the jr/ir loops.

**Comment by devinamatthews** [comment]
Click on one of the things that says "Environment: LIB_TYPE=......"

**Comment by fgvanzee** [comment]
> Click on one of the things that says "Environment: LIB_TYPE=......"

When I do that, the page is mostly blank. It worked when I clicked on the link you gave me above, though. It might be that my web browser sucks--who knows.

**Comment by devinamatthews** [comment]
I think the .def file is the last thing as the static Appveyor build passes now.

**Comment by isuruf** [comment]
I did something like `nm -g lib/haswell/libblis.so  | grep -o " T bli_.*" | grep -v haswell | grep -v zen | cut -f2- "-dT" | cut -f2- "-d "` last time.

**Comment by isuruf** [comment]
> @isuruf yes this PR means that "pthreads" on Windows is really just WinThreads. Of course, pthreads-win32 would also be based on WinThreads internally so I think there is really very little difference (apart from possible bugs...).

I see that in this PR, threading is disabled. Should we check that this works with threading enabled as well?

**Comment by fgvanzee** [comment]
> When I do that, the page is mostly blank. It worked when I clicked on the link you gave me above, though. It might be that my web browser sucks--who knows.

FWIW, once I cleared my web browser's cache, the Appveyor console rendered properly.

**Comment by fgvanzee** [comment]
> I did something like `nm -g lib/haswell/libblis.so | grep -o " T bli_.*" | grep -v haswell | grep -v zen | cut -f2- "-dT" | cut -f2- "-d "` last time.

Now that I can actually see the Appveyor console, I can debug our way back to a passing build at Appveyor. I'm going to try to write a script that will automatically re-generate the symbols file (which I am going to move to `build`).

**Comment by isuruf** [comment]
> why does your command strip out the symbols containing haswell or zen? Why are those symbols undesired for the symbols list file?

I assumed that the user doesn't want to call a architecture specific function and just call the function that dispatches to the correct specific function.

**Comment by fgvanzee** [comment]
Okay, so the symbol list file really is only for externally-accessible symbols. 

I also noticed that `BLIS_ONE`, `BLIS_ZERO`, etc. are not present in the existing symbols file. Though they are in the data section (not the text section) of the file, I assume we still need to export them? (I'm writing the script so that those are captured as well.)

**Comment by isuruf** [comment]
@fgvanzee, instead of writing a script, how about adding a `BLIS_EXPORT` to all the functions? (Like https://github.com/flame/blis/blob/d7537fb51dac0636591fc7c68261a2322642ab3c/frame/include/bli_extern_defs.h#L50)

I didn't add globals like `BLIS_ONE` to the def file because having it in the def file is not enough as `__declspec(dllimport)` has to be used when using the library.

**Comment by fgvanzee** [comment]
> instead of writing a script, how about adding a `BLIS_EXPORT` to all the functions?

@isuruf Thanks for pointing this out. Using a `BLIS_EXPORT` macro in front of every public symbol is indeed in my plans to do eventually, and I 100% agree that this is the right solution. However, I'm not quite ready to tackle that yet, so for now I'm just trying to get Appveyor builds back up and running.

**Comment by fgvanzee** [comment]
It appears that we have some more failures to deal with:

```
test_libblis.o : error LNK2019: unresolved external symbol pthread_barrier_init referenced in function libblis_test_init_strings
test_libblis.o : error LNK2019: unresolved external symbol pthread_create referenced in function libblis_test_init_strings
test_libblis.o : error LNK2019: unresolved external symbol pthread_join referenced in function libblis_test_init_strings
test_libblis.o : error LNK2019: unresolved external symbol pthread_barrier_destroy referenced in function libblis_test_init_strings
test_libblis.o : error LNK2019: unresolved external symbol pthread_barrier_wait referenced in function libblis_test_op_driver
test_libblis.x : fatal error LNK1120: 5 unresolved externals
clang.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
Makefile:779: recipe for target 'test_libblis.x' failed
make: *** [test_libblis.x] Error 96
```

BTW, what is the difference between the `pr` and `branch` CI builds shown below? Same question for `pr` and `push`.

**Comment by fgvanzee** [comment]
I think I more-or-less understand the problem now. The pthread functions being defined in `bli_pthread_wrap.c` aren't being exported from the DLL because they are not in the symbols list file. But then the testsuite is trying to link against some of these pthread functions. (That doesn't explain the weird "in function" parts of the error messages, but I'm willing to overlook that and assume the problem would go away if the testsuite could find the pthreads function symbols at link-time.)

My solution: add a `bli_pthread_*()` API that directly calls the corresponding pthread functions, and export these functions from the BLIS DLL. Then, call these `bli_pthread_*()` functions from the testsuite instead of the pthread functions directly.

**Comment by isuruf** [comment]
> My solution: add a bli_pthread_*() API to BLIS that directly calls the corresponding pthread functions, and export these functions from the BLIS DLL. Then, call these bli_pthread_*() functions from the testsuite instead of the pthread functions directly.

Here's another solution. For windows only, do
```
#define pthread_create bli_pthread_create
```
and export `bli_pthread_create` as you do now. This is what I did for `sleep` which was exported as `bli_sleep` for windows only.

**Comment by fgvanzee** [comment]
> and export `bli_pthread_create` as you do now. This is what I did for `sleep` which was exported as `bli_sleep` for windows only.

Can you point me to the specific files/lines in which you employ this trick for `sleep()`? I remember seeing it previously, but now I can't find it anymore. (I tried `grep -R sleep .` from the top-level directory.)

I agree that your suggested fix would work. By `#define`ing all of the `pthreads_*()` APIs to their `bli_pthreads_*()` equivalents, the source code for the testsuite does not need to change. There is a certain amount of elegance to this. However, I currently find myself drawn to changing the calls in the source code to `bli_pthread_*()`, probably because it is (at least to me) explicit and clear.

**Comment by fgvanzee** [comment]
> Can you point me to the specific files/lines in which you employ this trick for `sleep()`? I remember seeing it previously, but now I can't find it anymore. (I tried `grep -R sleep .` from the top-level directory.)

BTW, it seems entirely possible that I changed your Windows-only `#define sleep bli_sleep` so that instead the definition of `bli_sleep()` is determined by whether we're building for Windows, and then calling `bli_sleep()` from the testsuite. In fact, I have the vaguest of memories of doing this, but I can't be sure. If so, it would seem that I'm nothing if not consistent in my preferences. :) lol

**Comment by isuruf** [comment]
> However, I currently find myself drawn to changing the calls in the source code to bli_pthread_*(), probably because it is (at least to me) explicit and clear.

Sounds good. It was just a suggestion.

> Can you point me to the specific files/lines in which you employ this trick for sleep()? I remember seeing it previously, but now I can't find it anymore. (I tried grep -R sleep . from the top-level directory.)

Seems like it was removed. So it's consistent now.

> BTW, what is the difference between the pr and branch CI builds shown below? Same question for pr and push.

Push/branch CI jobs builds the branch and the PR jobs builds the branch merged into master. (Sometimes branch might succeed, but merging it to master might fail)

**Comment by fgvanzee** [comment]
> Push/branch CI jobs builds the branch and the PR jobs builds the branch merged into master. (Sometimes branch might succeed, but merging it to master might fail)

Thanks for that explanation. I hadn't realized the nuance that `pr` was testing what would happen if the branch was actually merged with master.

**Comment by fgvanzee** [comment]
Thanks @devinamatthews, @isuruf, and @honnibal for your help on this PR.

**Pull request merged**
