### PR TITLE
Export functions without def file

### LINKED ISSUE #248: Use -fvisibility=hidden and explicitly mark symbols for shared object export
Picking up on the discussion that developed in pull request #37, it would probably be best for BLIS to *not* automatically export all symbols in its shared libraries, but rather only export the ones that correspond to "public" APIs. 

In summary, this means:
- compiling with `-fvisibility=hidden`, which sets the default symbol visibility to hidden;
- marking all BLAS/CBLAS functions as public;
- marking some subset of BLIS typed API functions as public;
- marking some subset of BLIS object API functions as public.

Also, if the export statements (that mark a symbol as public) are macroized, the macro can be defined conditionally based on whether we are building a Linux shared object or a Windows DLL.

GNU gcc documentation on symbol visibility can be found [here](https://gcc.gnu.org/wiki/Visibility).

### PR DESCRIPTION
**Pull request by isuruf**
@fgvanzee, can you confirm that the functions removed from libblis-symbols.def file are not intended to be public API?

Fixes #248

### CODE REVIEW

**Comment by fgvanzee** [comment]
> @fgvanzee, can you confirm that the functions removed from libblis-symbols.def file are not intended to be public API?

@isuruf Yes, I will check. Thanks.

**Comment by fgvanzee** [comment]
@isuruf The functions you removed from `libblis-symbols.def` all appear to be internal/helper functions--no public functions that I could see.

**Comment by isuruf** [comment]
Ready for review.

`CFLAGS="-fvisibility=hidden" ./configure auto ` should remove those few internal functions from being exported now.

After this PR is merged, `BLIS_EXPORT_BLIS` macro should be removed from any internal API.

**Comment by fgvanzee** [comment]
> Ready for review.

Will do. Thanks Isuru.

> `CFLAGS="-fvisibility=hidden" ./configure auto` should remove those few internal functions from being exported now.

I think you are suggesting that we can now adjust the `Makefile` so that `-fvisibility=hidden` is always used? Please confirm.

Also, do you know if that compiler option recognized by all of: gcc, clang, and icc? If we need to use a different option for clang or icc (or both), that's fine. I just need to (eventually) know what the equivalent option(s) is/are.

> After this PR is merged, `BLIS_EXPORT_BLIS` macro should be removed from any internal API.

Got it. I'll add this to my near-term to-do list, though I have a lot on my plate in the next couple days, so it might not be until early next week that I can make significant progress on this.

Also, if you don't mind, I'll wait on merging this PR until I can remove the macros from the internal APIs (I'll push to the PR branch). That way, you can also easily review/comment on it before I merge.

**Comment by isuruf** [comment]
> I think you are suggesting that we can now adjust the `Makefile` so that `-fvisibility=hidden` is always used? Please confirm.

A user can easily pass the `-fvisibility=hidden` option or you can set it in the configure. 
I'll leave that up to you to decide what to do.

> Also, do you know if that compiler option recognized by all of: gcc, clang, and icc? If we need to use a different option for clang or icc (or both), that's fine. I just need to (eventually) know what the equivalent option(s) is/are.

I know that gcc and clang on unix do. (clang doesn't on windows). Not sure about icc.

> Also, if you don't mind, I'll wait on merging this PR until I can remove the macros from the internal APIs (I'll push to the PR branch). That way, you can also easily review/comment on it before I merge.

Sure. I'm not in a hurry.

**Comment by fgvanzee** [comment]
> A user can easily pass the `-fvisibility=hidden` option or you can set it in the configure.
I'll leave that up to you to decide what to do.

Understood. I'll probably make it a `configure` option eventually. But reducing it down to that flag's presence or absence is a great improvement. Thanks again for your efforts.

**Comment by fgvanzee** [comment]
@isuruf I was taking a closer look at the use of `BLIS_EXPORT_BLIS`. It seems that you mostly targeted function _prototypes_. However, the macro was also inserted into a few function _definitions_.

Can you briefly explain which one, prototypes or definitions, the macro must be used in front of in order to have the desired effect vis-a-vis hiding/exposing symbols in shared libraries?

**Comment by isuruf** [comment]
From prototypes I assume you mean function declaration. The macro should be added to the declaration and not the definition. If you can point out the definitions I have used the macro on, I'll fix them

**Comment by fgvanzee** [comment]
@isuruf Yes, I mean declaration. Not sure which term is in vogue these days; I call them prototypes since that was what they were called when I learned C. :)

You can find the affected source files by executing `grep -R BLIS_EXPORT_BLIS frame | sort | grep "\.c:" | less` at the top-level directory.

It may also be good to do the same thing but for `BLIS_EXPORT_BLAS`.

**Comment by fgvanzee** [comment]
@isuruf Your removal of `BLIS_EXPORT_BLIS`/`BLIS_EXPORT_BLAS` from function definitions looks good. I also appreciate that you did not leave behind the space after the macro! :)

**Comment by fgvanzee** [comment]
@isuruf I am now going through all of the remaining occurrences of `BLIS_EXPORT_BLIS` and remove the ones associated with functions that should always be private/internal.

**Comment by isuruf** [comment]
Thanks @fgvanzee

**Comment by fgvanzee** [comment]
Interesting observation: Because @isuruf wrote "Fixes #248" in the initial issue posting, merging this PR automatically closed #248. That seems like a generally smart and useful feature in GitHub, though not necessarily for those of us who start out oblivious to the effects of those magic words. :) It took me a little bit of digging to figure out what had happened.

Did you know about this, Isuru?

**Comment by fgvanzee** [comment]
> @isuruf I am now going to go through all of the remaining occurrences of `BLIS_EXPORT_BLIS` and remove the ones associated with functions that should always be private/internal.

@isuruf Done. Take a look at 5a5f494 for the finished product. (Everything else is merged back to `master`, now, too.)

**Comment by isuruf** [comment]
Thanks.  5a5f494 looks good to me. Maybe something in docs asking the user to add `-fvisibility=hidden` to hide private API would help.

Yes, the fixes word was intentional. Closes and resolves also work.

**Comment by fgvanzee** [comment]
Thanks for those pro-tips. I'll work on something for the docs. Or, perhaps we should open a new issue to discuss whether `-fvisibility=hidden` should be the default for building shared libraries of BLIS. (I am open to it.) Maybe a new `configure` option would help, too.

**Pull request merged**
