### PR TITLE
AMD specific optimizations for target 'zen'

### PR DESCRIPTION
**Pull request by nisanthmpamd**
Re-enabling the AMD specific optimizations for target 'zen', that were disabled while merging 'amd' branch to 'master' branch.

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thank you, Nisanth. This looks fine.

**Comment by cosstas** [comment]
Do the ongoing zen architecture optimizations at the 'amd' branch get merged to 'flame\master'?

**Comment by fgvanzee** [comment]
@cosstas I use the `amd` branch here at https://github.com/flame/blis for several purposes:
- A "merge point" marker from which the [downstream repository maintained by AMD](https://github.com/amd/blis) can pull.
- A temporary branch on which I can commit and test AMD/Zen-related changes originating from the SHPC group based here at The University of Texas at Austin.
- A staging area where I can test and modify contributions pushed from AMD's downstream repositories before merging them back with `master`.

As a general policy, I try to minimize the amount of time the `amd` branch diverges from `master`. This is why they often track closely with one another. Sometimes, `amd` falls behind for a while, but can easily be "fast-foward" merged with `master`.

Let me know if you still have any questions.

**Comment by cosstas** [comment]
@fgvanzee Thank you very much for the elaborate answer. It explains everything.

**Comment by fgvanzee** [comment]
@cosstas BTW, while AMD may have additional optimizations in the [repository they maintain](https://github.com/amd/blis), the "plain vanilla" (upstream) BLIS maintained here, at https://github.com/flame/blis, already yields decent performance on AMD systems. The [performance data we gathered on an AMD Epyc](https://github.com/flame/blis/blob/master/docs/Performance.md#epyc) was generated using our upstream BLIS source distribution.

**Pull request merged**
