### PR TITLE
Add symbol export macro for all functions

### PR DESCRIPTION
**Pull request by isuruf**
This PR doesn't change anything. Just adds an empty macro.

I'll send a separate PR for visibility changes since it'll be easier to review a smaller PR and this PR is too big to have a discussion.

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thanks for taking the initiative on this, Isuru. I assume this will move us close to solving issue #248?

**Comment by isuruf** [comment]
Yes, #248 and #301

**Comment by fgvanzee** [comment]
@isuruf Are you comfortable with merging this now?

**Comment by isuruf** [comment]
Yes, this PR doesn't change anything, so ready for merging

**Pull request merged**
