### PR TITLE
Generate makefile fragments in build tree

### LINKED ISSUE #237: Out-of-tree build with read-only source fails
Attempting to build out-of-tree while the source directory is mounted (or has permissions set to) read-only fails due to trying to generate Makefile fragments:

```
configure: creating makefile fragments in /home/dmatthews/src/blis/config/sandybridge
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/config/sandybridge/.fragment.mk: Read-only file system
configure: creating makefile fragments in /home/dmatthews/src/blis/kernels/sandybridge
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/kernels/sandybridge/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/kernels/sandybridge/3/.fragment.mk: Read-only file system
configure: creating makefile fragments in /home/dmatthews/src/blis/ref_kernels
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/1/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/1f/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/1m/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/3/.fragment.mk: Read-only file system
/home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: 224: /home/dmatthews/src/blis/build/gen-make-frags/gen-make-frag.sh: cannot create /home/dmatthews/src/blis/ref_kernels/ind/.fragment.mk: Read-only file system
configure: creating makefile fragments in /home/dmatthews/src/blis/frame
...
```

If we really have to generate such things, they should go in the build tree.

### PR DESCRIPTION
**Pull request by devinamatthews**
Fixes #237

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thanks for digging into this, Devin. Just curious: did you prioritize this because you needed it for your own work, or some other reason? (I know organizations like TACC would find this useful.)

**Comment by devinamatthews** [comment]
I decided to switch to using a Linux VM on my Mac for development, and it is safer (and maybe faster?) to mount shared folders as read-only (the source is on the host as I still edit it there with Eclipse).

**Comment by fgvanzee** [comment]
@devinamatthews Makes sense now. Thanks.

I've reviewed the changes and plan to merge relatively shortly, followed by a whitespace cleanup. :)

**Comment by devinamatthews** [comment]
Spaces man, learn to love 'em.

**Comment by fgvanzee** [comment]
I use spaces, just not where I use tabs. :)

**Pull request merged**
