### PR TITLE
Fix windows build and enable x86_64 on appveyor

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by fgvanzee** [comment]
```
The command ./travis/do_sde.sh exited with 2.
Log:
+SDE_VERSION=sde-external-8.16.0-2018-01-30-lin
+SDE_TARBALL=sde-external-8.16.0-2018-01-30-lin.tar.bz2
+SDE=sde-external-8.16.0-2018-01-30-lin/sde64
+set +x
+tar xvf sde-external-8.16.0-2018-01-30-lin.tar.bz2
tar: This does not look like a tar archive
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/home/travis/.travis/job_stages: line 190: 11512 Terminated 
```

@devinamatthews Is the Travis SDE failure above the same as last time--the dropbox bug that we never understood?

**Comment by devinamatthews** [comment]
Yes. There is a Travis environment variable that you can check to see if you are in a secure build, and if not skip the SDE run.

**Comment by devinamatthews** [comment]
`$TRAVIS_PULL_REQUEST`

**Comment by devinamatthews** [comment]
I just added #231 which should fix the test failures on PRs.

**Comment by devinamatthews** [comment]
@isuruf if you merge from dev the tests should pass now (at least the SDE error shouldn't happen).

**Comment by isuruf** [comment]
I changed the target branch to `dev`

**Comment by fgvanzee** [comment]
Thanks for your help, Devin.

**Pull request merged**
