### PR TITLE
Add BLIS_EXPORT_BLIS to bli_abort.

### LINKED ISSUE #428: Quest: undefined reference to 'blis_abort'
hello，
        After installing the blis with configure 'zen', I tryied #include "blis.h" in my code. But, when I compile it with command "gcc -fopenmp -lm -lblis *.c -o a.out", I receive the error of ld as written by my title.
        Besides, when I tried commands :  "gcc -fopenmp -c *.c -o *.o" & "gcc *.o $(PREFIX)/lib/zen/libblis.a -fpenmp -lm -o a.out", I make it successfully. How to solve  or explain this question?

### PR DESCRIPTION
**Pull request by devinamatthews**
Fixes #428.

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thanks for identifying this fix, Devin. But I can't quite figure out what was leading it to be needed in the first place.

**Comment by devinamatthews** [comment]
My understanding is that there is at least one inline function in blis.h that calls bli_abort. Since such a function would result in a call to bli_abort *in user code*, then the symbol must be exported in the .so.

**Comment by fgvanzee** [comment]
> Since such a function would result in a call to bli_abort *in user code*, then the symbol must be exported in the .so.

This is the case even if the function is a static/inline function that is never invoked in the user code?

**Comment by devinamatthews** [comment]
Without optimization, yes. This would break user debug builds.

**Pull request merged**
