### PR TITLE
Use -O2 for all framework code.

### LINKED ISSUE #341: checkblas failure for cortexa53
I'm puzzled by this and don't have the enthusiasm to debug it, but thought I should at least record it.

I built for the cortexa53 target on aarch64, and make checkblas failed with the errors below. However, the full blis test succeeded.  This was on a thunderx1 KVM VM with gcc 8.3.1 under Fedora 29.  It also fails if I build the Fortran version directly.

However, the test passes doing the same thing on a cortexa72 VM ("Amazon Linux 2") with gcc 7.3.1 (Red Hat 7.3.1-5).

```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .167333    ,    .442557    )  (    .167333    ,    .442557    )
       2  (    .217320    ,    .108337    )  (    .217320    ,    .108337    )
       3  (    .329789    ,   -.166362E-01)  (    .329789    ,   -.166362E-01)
       4  (    .250089    ,   -.910139E-01)  (   -.609890E+10,   -.275225E+10)
       5  (    .796754    ,   -.565034E-01)  (    .796754    ,   -.565034E-01)
 ******* CTBMV  FAILED ON CALL NUMBER:
    747: CTBMV ('L','N','U',  5,  4, A,  6, X, 2)                               .

 CTPMV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .686813    ,   -.156843    )  (    .686813    ,   -.156843    )
       2  (   -.101935    ,    .100522    )  (   -.101935    ,    .100522    )
       3  (   -.365189E-01,    .520084E-01)  (   -.365189E-01,    .520084E-01)
       4  (    .305346    ,    .135281    )  (   -.529970E+10,    .843656E+10)
       5  (    .884216    ,    .264764    )  (    .884216    ,    .264764    )
 ******* CTPMV  FAILED ON CALL NUMBER:
    171: CTPMV ('L','N','U',  5, AP, X, 2)                                      .


 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .749251E-02,    .242757    )  (   -32.3105    ,    128.059    )
       2  (     .00000    ,     .00000    )  (    .349610E-01,   -.424232    )
       3  (    .167333    ,    .306693    )  (   -.229271E+10,   -.484016E+10)
       4  (    .796703    ,    .298701    )  (    .796703    ,    .298701    )
       5  (    .127373    ,   -.356643    )  (    .127373    ,   -.356643    )
 ******* CTBSV  FAILED ON CALL NUMBER:
    723: CTBSV ('U','N','U',  5,  4, A,  6, X, 2)                               .

 CTPSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .926573    ,   -.356643    )  (    .160330    ,    .189820    )
       2  (     .00000    ,     .00000    )  (    .683755E-01,    .389953E-01)
       3  (    .117383    ,    .498502    )  (   -.271229E+10,   -.426074E+10)
       4  (    .247253    ,    .429570E-01)  (    .247253    ,    .429570E-01)
       5  (    .774226E-01,   -.348651    )  (    .774226E-01,   -.348651    )
 ******* CTPSV  FAILED ON CALL NUMBER:
    147: CTPSV ('U','N','U',  5, AP, X, 2)                                      .
```

### LINKED ISSUE #342: checkblas failures with generic target
I built current master on power8 ppc64le (Fedora 29) with
```
CFLAGS=-mcpu=power8 ./configure generic
```
and got the following failures from checkblas, though checkblis passed:

```
cblat2:

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .367133    ,    .442557    )  (    .367133    ,    .442557    )
       2  (    .619742    ,    .145569    )  (    .619742    ,    .145569    )
       3  (    .419282    ,   -.274696    )  (    .419282    ,   -.274696    )
       4  (    .113902    ,   -.162085    )  (    .497250E-01,    .797809E-01)
       5  (    .438563E-01,    .402786    )  (    .438562E-01,    .402786    )
       6  (    .939156    ,    .138420    )  (    .664142    ,   -.405661    )
       7  (    .455686    ,   -.675104E-01)  (    .455686    ,   -.675104E-01)
       8  (   -.154942E-02,    .266114    )  (   -.150000E+11,    .602897E+10)
       9  (   -.938862E-01,    1.08419    )  (   -.938862E-01,    1.08419    )
 ******* CTPMV  FAILED ON CALL NUMBER:
    219: CTPMV ('L','N','U',  9, AP, X, 2)                                      .

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .277223    ,   -.348651    )  (    .185920E+10,    .546762E+12)
       2  (    .806693    ,   -.492507    )  (   -.940210E+09,    .547188E+12)
       3  (    .966533    ,    .442557    )  (   -.228236E+09,   -.136729E+10)
       4  (     .00000    ,     .00000    )  (   -.677304E+09,   -.137215E+09)
       5  (    .926573    ,    .106893    )  (    .197802E+20,   -.154845E+20)
       6  (    .956543    ,   -.100899    )  (    .239256E+09,   -.503443E+10)
       7  (    .686813    ,   -.156843    )  (    .176324E+10,    .214785E+09)
       8  (    .247253    ,   -.292707    )  (    .247253    ,   -.292707    )
       9  (    .774226E-01,    .989011E-01)  (    .774226E-01,    .989011E-01)
 ******* CTPSV  FAILED ON CALL NUMBER:
    195: CTPSV ('U','N','U',  9, AP, X, 2)                                      .

cblat3:

 CHEMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* CHEMM  FAILED ON CALL NUMBER:
    256: CHEMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

 CSYMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* CSYMM  FAILED ON CALL NUMBER:
    256: CSYMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

zblat3:

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* ZHEMM  FAILED ON CALL NUMBER:
    256: ZHEMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

 ZSYMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* ZSYMM  FAILED ON CALL NUMBER:
    256: ZSYMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .
```

Then I checked the generic config on skx with -march=skylake-avx512, and also with -march=haswell, and got similar results.

I guess #341 is related.

### PR DESCRIPTION
**Pull request by devinamatthews**
It seems that -O3 might be causing intermittent problems with the f2c'ed packed and banded code. -O3 is retained for kernel code. Fixes #341 and fixes #342.

### CODE REVIEW

**Comment by devinamatthews** [comment]
This is assumed to fix the problem given the commit referenced in #341.

**Comment by fgvanzee** [comment]
Someone with ARM knowledge should resolve this conflict. (I would just be guessing.)

**Comment by devinamatthews** [comment]
@fgvanzee it's just a result of merging #353.

**Comment by fgvanzee** [comment]
Thanks. That's what I get for peeking inside of my github mail filter folder.

**Comment by fgvanzee** [comment]
@devinamatthews Just to clarify, this will result in, for example, `haswell` kernel code being compiled with
```
... -O2 -O3 -fomit-frame-pointer ...
```
Is this guaranteed to result in `-O3` taking precedence?

**Comment by devinamatthews** [comment]
gcc, icc, xlc: confirmed. clang: docs are crap and don't say but they usually do what gcc does.

**Comment by fgvanzee** [comment]
Thanks for checking. I suppose if it ever becomes a problem, we can make the two variables mutually exclusive.

**Pull request merged**
