### PR TITLE
Add test for skx (only on Linux).

### PR DESCRIPTION
**Pull request by devinamatthews**

### CODE REVIEW

**Comment by devinamatthews** [comment]
Ugh, apparently we need to tweak the binutils to get -march=skylake-avx512 to work. I'll have to remember what I did for TBLIS.

**Comment by jeffhammond** [comment]
Theoretically, if you used opcodes directly instead of mnemonics, you
wouldn’t need binutils support, no?

Ugh, apparently we need to tweak the binutils to get -march=skylake-avx512
> to work. I'll have to remember what I did for TBLIS.
>
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by devinamatthews** [comment]
@jeffhammond you forgot the <sarcasm> tag... but seriously we do this for `xgetbv` in the CPUID code.

**Comment by devinamatthews** [comment]
Obsoleted.

**Pull request closed without merging**
