### PR TITLE
Arm64 Row-Major d8x6

### PR DESCRIPTION
**Pull request by xrq-phys**
Basically it's a templated re-implementation of current column-major d6x8's transpose.

Shall I test out `gemmtrsm`?

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thanks @xrq-phys! (@jdiamondGitHub will definitely be interested in this.)

> Shall I test out `gemmtrsm`?

You are welcome to give it a try! It would have a great benefit for `trsm` users. :slightly_smiling_face: 

Contact me on Discord if you have any questions regarding the semantics of `gemmtrsm`. It can be confusing the first time, especially the `_u` (upper triangular) instance since it moves backwards (bottom-right to top-left).

**Comment by jdiamondGitHub** [comment]
Yes, thank you so much @xrq-phys. :)  We are in a crunch at the moment, but we'll try to give it a run within the next week.

**Comment by fgvanzee** [comment]
Okay, I'll merge this now. Thanks for taking a look at the microkernel changes, @xrq-phys (and @figual)! We'll keep you informed if/when we make any further changes to the `armv8a` ukernels.

**Comment by fgvanzee** [comment]
(Apologies @xrq-phys and @figual for the earlier (deleted) message: I got my PRs mixed up.)

**Comment by fgvanzee** [comment]
Closing this PR. With the merging of #655, it is now moot. Thanks @xrq-phys!

**Pull request closed without merging**
