### PR TITLE
Update do_sde.sh

### LINKED ISSUE #319: get SDE from the right place
https://github.com/mmcloughlin/meow/blob/871e50784daff1c9ec5ef66fe3d8fda6bbcd42cf/.travis.yml is a way better way to download SDE than my hack.  They are very smart.  We should emulate their smartness.

The important part is the following, which I verified locally:
```yaml
install:
- export "SDE_VERSION_NAME=sde-external-8.16.0-2018-01-30-lin"
- curl --verbose
       --form accept_license=1
       --form form_id=intel_licensed_dls_step_1
       --output /dev/null
       --cookie-jar jar.txt
       --location
       https://software.intel.com/protected-download/267266/144917
- curl --verbose
       --cookie jar.txt
       --output sde.tar.bz2
       https://software.intel.com/system/files/managed/2a/1a/${SDE_VERSION_NAME}.tar.bz2
```

### PR DESCRIPTION
**Pull request by devinamatthews**
Automatically accept SDE license and download directly from Intel. Fixes #319.

### CODE REVIEW

**Comment by fgvanzee** [comment]
Does this mean we no longer need the secret token thingy in `.travis.yml`? I vaguely recall needing it, but I don't recall exactly why.

**Comment by devinamatthews** [comment]
Yes, this would remove the need for the secret token and the Dropbox shenanigans.

**Comment by devinamatthews** [comment]
Removed the secret key.

**Comment by fgvanzee** [comment]
Sweet. I'll wait for AppVeyor and then merge if green.

**Comment by devinamatthews** [comment]
Hold on, I forgot to enable SDE for PRs.

**Comment by jeffhammond** [comment]
👍🏻
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Pull request merged**
