### PR TITLE
Don't override -mcpu with -march on ARM

### PR DESCRIPTION
**Pull request by loveshack**
Use -mcpu for ARM
See the GCC doc about -march, -mtune, and -mpu and maybe
https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu

### CODE REVIEW

**Comment by fgvanzee** [comment]
@loveshack Thanks Dave. In case you hadn't seen already, it looks like one of the Travis CI tests failed:
```
arm-linux-gnueabihf-gcc: error: unrecognized argument in option ‘-mcpu=cortexa15’
```
Also, I'd like to give @figual and @dnparikh a chance to comment here since they have more ARM experience than me.

**Comment by loveshack** [comment]
I fixed the typo, thanks.  I thought I'd tested it and forgotten to submit.

**Comment by devinamatthews** [comment]
@fgvanzee I think this is ready to merge.

**Comment by fgvanzee** [comment]
Hmm, sorry for the delay, @loveshack . Not sure how this slipped through the cracks.

**Pull request merged**
