### PR TITLE
resubmit of AOCL 2.0

### PR DESCRIPTION
**Pull request by rsanagap**
re-submitting pull request to flame:amd branch

### CODE REVIEW

**Comment by fgvanzee** [comment]
Thanks for this resubmit against `flame:amd`, @rsanagap. I'll begin working on this shortly.

**Comment by rsanagap** [comment]
Hi Field(@fgvanzee )
do you have some tentative date by which these changes would be taken to master branch ?

**Comment by fgvanzee** [comment]
@rsanagap I will merge `amd` into `master` on Monday. Thanks for your patience!

**Comment by fgvanzee** [comment]
@rsanagap I've completed the merge. Please review the `git log` going back to 29b0e1ef (Oct 11) to see what tweaks I made to your contributions for upstream. Also note that I disabled the call to `bli_gemm_small()` in `bli_gemm_front.c` by wrapping that code in an `#if 0` cpp macro conditional. You may wish to re-enable this when you `git pull` back to your downstream `amd/blis`. I also moved some of the notrans/trans logic around the call to `bli_syrk_small()` into the function itself in order to bring the calling code into harmony with corresponding code fragments that call `bli_gemm_small()` and `bli_trsm_small()`. Aside from these things, most of the changes I made were minor.

**Pull request merged**
