### PR TITLE
L3 oapi without macros

### PR DESCRIPTION
**Pull request by devinamatthews**
Simplify the l3 oapi by removing the rather unnecessary macro layer. This is an example of how many parts of BLIS which are currently macros, but don't really need to be could be potentially improved (I guess it depends on your viewpoint though :smile:).

### CODE REVIEW

**Comment by devinamatthews** [comment]
@fgvanzee I think this is actually ready to merge now. All of the L3 operations have the full interface (_ex, nat, ind, etc.) and all of the tests past.

**Comment by fgvanzee** [comment]
I found a regression. Previously, calling `herk` (for example) with a C that is tagged `BLIS_GENERAL` (instead of `BLIS_HERMITIAN`) would have triggered a runtime error. It seems that this code no longer checks for the expected `struc_t` value. Was this intentional?

**Comment by devinamatthews** [comment]
If I reinstate the `_check` routines, is calling them from the oapi layer sufficient?

**Comment by devinamatthews** [comment]
Shouldn't `gemmt` be doing the check on `C`?

**Comment by fgvanzee** [comment]
I'm also seeing that you made a pretty big reorganization of the files that do the expert vs. non-expert API.

I think I'm going to need quite a bit more time to review this.

**Comment by fgvanzee** [comment]
> If I reinstate the `_check` routines, is calling them from the oapi layer sufficient?

I think that would be okay, yes. Was there some other alternative that you had in mind?

**Comment by devinamatthews** [comment]
> > If I reinstate the _check routines, is calling them from the oapi layer sufficient?

> I think that would be okay, yes. Was there some other alternative that you had in mind?

No, I just didn't know if this had to happen in `_front` specifically. I will add the check functions back in. BTW none of this is actually tested in the testsuite :).

**Comment by fgvanzee** [comment]
> > > If I reinstate the _check routines, is calling them from the oapi layer sufficient?
> 
> > I think that would be okay, yes. Was there some other alternative that you had in mind?
> 
> No, I just didn't know if this had to happen in `_front` specifically. I will add the check functions back in. BTW none of this is actually tested in the testsuite :).

I have confirmed that the only thing that happens between `bli_l3_oapi.c` and the calling of the `_front()` functions is getting the context and runtime `structs` squared away.

**Comment by devinamatthews** [comment]
@fgvanzee I added back the error checking.

**Comment by devinamatthews** [comment]
@fgvanzee should be ready to merge.

**Comment by fgvanzee** [comment]
Thanks, I'll start reviewing it.

**Comment by fgvanzee** [comment]
@devinamatthews Turns out we *did* need the `if ( !cntx )` conditional after all, because operations like `herk` call their `_check()` function before the `cntx_t*` is valid (which doesn't happen until `gemmt` is called).

BUT, I decided to solve it by moving the `bli_check_sufficient_stack_buf_size()` call into the gks, since that was where we agreed we would go eventually anyway.

**Comment by fgvanzee** [comment]
I'll put together a squash-merge commit log and then squash-merge later today.

**Pull request merged**
